### ISSUE TITLE
Confidence String or Float?

### ISSUE THREAD

**Issue by BOsterbuhr** [Lambda-School-Labs/human-rights-first-police-ds-a#63]
### This has been bugging me, so I wanted to get everyone's input.

> This is extremely nitpicky and does not need to be addressed with any urgency.

<br>

In `aws_app/app/scraper.py`, the function `frankenber_rank()` returns confidence in two formats. First formatted as a string `f"{100 * conf:.2f}%"` then again as a float in the `raw _data` tuple. 
https://github.com/Lambda-School-Labs/human-rights-first-police-ds-a/blob/9116033eb228e3c25fca2024242023045b8b3e6a/aws_app/app/scraper.py#L15-L27

If we now look at `scrape_twitter()` `conf_str` and `conf_float` are defined on lines 65 and 66 respectively, even though only `conf_float` is used.

I like that `conf_str` is a nicely formatted string and think it should replace `conf_float` on line 75. But.....
https://github.com/Lambda-School-Labs/human-rights-first-police-ds-a/blob/9116033eb228e3c25fca2024242023045b8b3e6a/aws_app/app/scraper.py#L64-L79

## The issue
In `aws_app/app/db.py`, the `force_ranks` table has been initialized with `confidence` as `FLOAT` and not `TEXT`.
https://github.com/Lambda-School-Labs/human-rights-first-police-ds-a/blob/9116033eb228e3c25fca2024242023045b8b3e6a/aws_app/app/db.py#L55-L72
<br>
Also, I am not sure where `confidence` is even used on the site. I couldn't see anything on the admin side; does anyone know where it is actually displayed?

**Comment by rhiag** [comment]
I think when you speak of confidence you think of what percentage of confidence and it could be why it is being represented as a float and not string in the database. As to where this is being used - I see the confidence level show when you make a prediction using the FrankenBert model on the DS API. However that particular endpoint is being used just for demonstration and testing purposes.

**Comment by BOsterbuhr** [comment]
I forgot about the model API, thanks for the reminder.

I agree and understand the utility of using it as a float, especially when checking if it falls within a specific range. Although, using it in string form where it is formatted nicely (adding a % sign and rounding) may be helpful if we plan on displaying it to the admin. Do we plan on showing the confidence level to the admin when they are verifying an incident report? I seem to remember that being discussed.

**Comment by rhiag** [comment]
You are right. There was definitely a conversation regarding having that set up so as to aid the admin's work on accepting and rejecting the incident report.

**Comment by BOsterbuhr** [comment]
Closing, next labs can take a look at this if needed.
