### ISSUE TITLE
User name being inputted is not screen name

### ISSUE THREAD

**Issue by RowenWitt** [Lambda-School-Labs/human-rights-first-police-ds-a#71]
It looks like the user_name being uploaded each time the bot scrapes is not the screen_name, and is not very useful.  As a temporary fix I can just strip the user_name from the status, but if deemed the correct approach, it may be worthwhile to write a function to go back through and fix all of them from the SRC column.  It looks like the change occurred on August 5th.  Good news is it'll be easy to fix, honestly it seems like something I'd do, but I can't figure out when that chunk of code was changed.  
![Screen Shot 2021-08-14 at 7 46 43 PM](https://user-images.githubusercontent.com/81643616/129465276-bdf27f9e-64b0-4655-9a4b-c32d76f569a1.png)
To fix going forward, all that needs to be changed is switching line 73 to say `tweet.user.screen_name` instead of `tweet.user.user_name`.  Very easy fix, but that won't fix the old entries from about id 1330 to now (when sorted by id).  For that a simple function would need to be applied once to grab the user_name from the tweet SRC.

**Comment by BOsterbuhr** [comment]
Good catch; it looks like the change happened [here](https://github.com/Lambda-School-Labs/human-rights-first-police-ds-a/pull/56).  So any entries to the database after July 29th will have the "name" and not the "screen_name."

**Comment by RowenWitt** [comment]
Sweet, great find on when the change occurred.

**Comment by RowenWitt** [comment]
Fixed
