### ISSUE TITLE
Decreasing Torch size for deployment

### ISSUE THREAD

**Issue by RowenWitt** [Lambda-School-Labs/human-rights-first-police-ds-a#72]
Currently our requirements.txt is requiring `torch==1.9.0`, this includes all of the Torch library, about half of which is related to training, not inference.  We could reduce the size of our Torch import from about 830 MB down to maybe 300-400 MB.
Currently the version being downloaded onto the EC2 instance(s) (I'm not sure how this works, would be cool if they shared environments somehow) is `torch-1.9.0-cp37-cp37m-manylinux1_x86_64.whl` and we could probably replace this with the cpu only version by using the below in our requirements 
`--find-links https://download.pytorch.org/whl/torch_stable.html `
`torch==1.9.0+cpu`
per https://github.com/pytorch/pytorch/issues/29745
instead of the current
`torch==1.9.0`

There might be a reason we're installing the whole thing, but I don't know what it is.

If we need Torch for our venvs when building stuff for the repo, we could initialize a new Pipenv based on the requirements, then install the Torch version you need (may need to unintall the Torch CPU version first), then do model training from there.  It might just make sense to train a model in a separate environment with full Torch 1.9.0 installed then export the model.

**Comment by JAaron93** [comment]
I'm glad you bring this up, Rowen. I was just thinking about how we could shrink BERTs size. It's too monstrous of a model to handle. 

I believe we should opt for a GPU-only install of Torch, `torch==1.9.0+cu111` The model already takes ~4 hours to train on NVIDIA P5000 GPUs and whichever GPUs Colab randomly distributes to its users. With only CPU it would take an unreasonable amount of time to train.

I'm not sure why they have the whole thing either, perhaps it was an oversight? If it isn't an oversight and it truly is needed then yes, I agree, training in a separate environment altogether before exporting the model might be necessary.

**Comment by RowenWitt** [comment]
Totally agree for training, using a GPU version is crucial for these bigger models, but on the inference side the CPU version is necessary as well, though I do think it's possible to do inference on GPUs, it takes a little bit of doing and our virtual machines won't have GPUs anyways.
