### ISSUE TITLE
FrankenBert prediction endpoint throws internal server error

### ISSUE THREAD

**Issue by RowenWitt** [Lambda-School-Labs/human-rights-first-police-ds-a#82]
![Screen Shot 2021-08-21 at 3 04 46 PM](https://user-images.githubusercontent.com/81643616/130335924-d0796eaa-6a62-4a86-927c-be3676e3c91a.png)

user_input.text is throwing an error -- Seems like a holdover from a point in which FrankenBert prediction was a post request.  Simple solution is to remove .text.

**Comment by RowenWitt** [comment]
Changed code in Josh's PR

**Comment by JAaron93** [comment]
Yup! Resolved the issue with my pull request. Thanks for bringing this to my attention.
